name: .NET CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore BookingSystem.Api.slnx

      - name: Build
        run: dotnet build BookingSystem.Api.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test BookingSystem.Api.Tests/BookingSystem.Api.Tests.csproj --configuration Release --no-build --verbosity normal